# Generated by Django 5.1.6 on 2025-02-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_membership_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['member_id'], 'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.AddField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件'),
        ),
        migrations.AddField(
            model_name='membership',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='membership',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='姓氏'),
        ),
        migrations.AddField(
            model_name='membership',
            name='member_id',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='會員編號'),
        ),
        migrations.AddField(
            model_name='membership',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話號碼'),
        ),
    ]
