# Generated by Django 5.1.6 on 2025-02-09 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_membership_options_membership_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_id',
            field=models.CharField(default='1001', max_length=4, unique=True, verbose_name='會員編號'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='簽到時間')),
                ('attendance_date', models.DateField(auto_now_add=True, verbose_name='出席日期')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membership', verbose_name='會員')),
            ],
            options={
                'verbose_name': '出席記錄',
                'verbose_name_plural': '出席記錄',
                'ordering': ['-attendance_date', '-check_in_time'],
                'unique_together': {('member', 'attendance_date')},
            },
        ),
    ]
